# Generated by Django 5.1.7 on 2025-03-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
