# Generated by Django 5.1.7 on 2025-05-02 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="picture",
            name="items",
        ),
        migrations.AddField(
            model_name="picture",
            name="square_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="item_pictures/squares/",
                verbose_name="Squared Image (e.g., 500x500)",
            ),
        ),
        migrations.AddField(
            model_name="picture",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="item_pictures/thumbnails/",
                verbose_name="Thumbnail (150x150)",
            ),
        ),
        migrations.AlterField(
            model_name="picture",
            name="picture",
            field=models.ImageField(
                upload_to="item_pictures/originals/", verbose_name="Original Image"
            ),
        ),
    ]
