# Generated by Django 5.2.1 on 2025-06-11 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FakturoidInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fakturoid_id",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Fakturoid ID"
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=100, verbose_name="Invoice Number"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="CZK", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "download_url",
                    models.URLField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Download URL",
                    ),
                ),
                (
                    "raw_data",
                    models.JSONField(blank=True, null=True, verbose_name="Raw Data"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fakturoid_invoices",
                        to="ufo_shop.order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fakturoid Invoice",
                "verbose_name_plural": "Fakturoid Invoices",
                "ordering": ["-created_at"],
            },
        ),
    ]
