# Generated by Django 5.2.1 on 2025-06-30 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0002_fakturoidinvoice"),
    ]

    operations = [
        migrations.CreateModel(
            name="Issuer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Name")),
                ("address", models.TextField(verbose_name="Address")),
                ("city", models.CharField(max_length=100, verbose_name="City")),
                (
                    "postal_code",
                    models.CharField(max_length=20, verbose_name="Postal Code"),
                ),
                (
                    "country",
                    models.CharField(
                        default="Czech Republic", max_length=100, verbose_name="Country"
                    ),
                ),
                (
                    "registration_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Registration ID (IČO)",
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Tax ID (DIČ)",
                    ),
                ),
                (
                    "bank_account",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Bank Account",
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="IBAN"
                    ),
                ),
                (
                    "swift",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="SWIFT"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="issuer_logos/",
                        verbose_name="Logo",
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="Default Issuer"),
                ),
            ],
            options={
                "verbose_name": "Invoice Issuer",
                "verbose_name_plural": "Invoice Issuers",
            },
        ),
        migrations.CreateModel(
            name="Invoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_number",
                    models.CharField(max_length=100, verbose_name="Invoice Number"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "due_date",
                    models.DateField(blank=True, null=True, verbose_name="Due Date"),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        verbose_name="Total Amount",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="CZK", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="invoices/",
                        verbose_name="PDF File",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="invoices",
                        to="ufo_shop.order",
                    ),
                ),
                (
                    "issuer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoices",
                        to="ufo_shop.issuer",
                    ),
                ),
            ],
            options={
                "verbose_name": "Invoice",
                "verbose_name_plural": "Invoices",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="FakturoidInvoice",
        ),
    ]
