# Generated by Django 5.1.7 on 2025-05-02 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0002_remove_picture_items_picture_square_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pictures",
                to="ufo_shop.item",
                verbose_name="Item",
            ),
            preserve_default=False,
        ),
    ]
