# Generated by Django 5.1.7 on 2025-05-10 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0003_picture_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="picture",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Uploaded by",
            ),
        ),
    ]
