# Generated by Django 5.2.1 on 2025-07-02 11:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0003_issuer_invoice_delete_fakturoidinvoice"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="needs_receipt",
        ),
        migrations.RemoveField(
            model_name="order",
            name="receipt_fee",
        ),
        migrations.AddField(
            model_name="item",
            name="base_price",
            field=models.IntegerField(
                default=0,
                help_text="This is the price that goes to your pocket. A 10% service fee will be added automatically.",
                verbose_name="Base Price (without service fee)",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.IntegerField(
                default=0, editable=False, verbose_name="Final Price (with service fee)"
            ),
        ),
    ]
