# Generated by Django 5.1.7 on 2025-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0004_picture_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="contact_email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Contact Email"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="contact_phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Contact Phone"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="fulfilled_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fulfilled At"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Payment ID"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Payment Method"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Shipped At"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Shipping Address"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Shipping Cost"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Country"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="State/Province"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_zip",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="ZIP/Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Subtotal"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Total"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.IntegerField(
                choices=[
                    (1, "In Cart"),
                    (2, "Ordered"),
                    (3, "Paid"),
                    (4, "Shipped"),
                    (5, "Fulfilled"),
                    (6, "Cancelled"),
                ],
                default=1,
                verbose_name="Status",
            ),
        ),
    ]
