# Generated by Django 5.2.1 on 2025-08-13 14:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ufo_shop",
            "0004_remove_order_needs_receipt_remove_order_receipt_fee_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
    ]
