# Generated by Django 4.2.3 on 2025-03-06 18:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "ufo_shop",
            "0004_remove_itemincart_amount_remove_itemincart_category_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="itemincart",
            old_name="quantity",
            new_name="amount",
        ),
    ]
