# Generated by Django 5.1.7 on 2025-05-14 06:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0005_order_contact_email_order_contact_phone_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="location",
        ),
        migrations.AddField(
            model_name="item",
            name="locations",
            field=models.ManyToManyField(
                blank=True, to="ufo_shop.location", verbose_name="Pickup Locations"
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="is_universal",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this location will be available for all merchandisers",
                verbose_name="Universal Location",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="note",
            field=models.TextField(
                blank=True, null=True, verbose_name="Additional Note"
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="pickup_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="ufo_shop.location",
                verbose_name="Pickup Location",
            ),
        ),
    ]
