# Generated by Django 5.1.7 on 2025-05-14 11:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0006_remove_item_location_item_locations_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="needs_receipt",
            field=models.BooleanField(
                default=False,
                help_text="If checked, a 7% fee will be added for receipt processing",
                verbose_name="Needs Receipt",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="receipt_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Receipt Fee"
            ),
        ),
    ]
