# Generated by Django 4.2.3 on 2025-03-06 18:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0006_itemincart_created_at_order_created_at_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ItemInCart",
            new_name="OrderItem",
        ),
    ]
