# Generated by Django 4.2.3 on 2025-03-06 18:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ufo_shop", "0007_rename_itemincart_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="supplier",
            new_name="merchandiser",
        ),
        migrations.AddField(
            model_name="location",
            name="merchandiser",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
