# Generated by Django 5.1.7 on 2025-05-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ufo_shop", "0008_news"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="color",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Color"
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="is_variant",
            field=models.BooleanField(default=False, verbose_name="Is Variant"),
        ),
        migrations.AddField(
            model_name="item",
            name="parent_item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="variants",
                to="ufo_shop.item",
                verbose_name="Parent Item",
            ),
        ),
    ]
